{% set name = "amici" %}
{% set version = "0.11.18" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b907a081aecea70751885ff1d37ef82944b134e541c3a01a5299a95b30d45efd

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"
  skip: true  # [win or py<37]
  script_env:
    - BLAS_LIBS="-lopenblas"


requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - numpy>=1.19.3
    - pip
    - python>=3.7
    - swig>=4
    - _openmp_mutex
    - libstdcxx-ng
    - libgcc-ng
    - pandas
    - sympy
    - openblas-devel
    - openblas
  host:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - numpy>=1.19.3
    - pip
    - python>=3.7
    - swig>=4
    - _openmp_mutex
    - libstdcxx-ng
    - libgcc-ng
    - pandas
    - sympy
    - openblas-devel
    - openblas
  run:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - numpy>=1.19.3
    - pip
    - python>=3.7
    - swig>=4
    - _openmp_mutex
    - libstdcxx-ng
    - libgcc-ng
    - pandas
    - sympy
    - openblas-devel
    - openblas
test:
  requires:
    - python-libsbml
    - toposort
    - wurlitzer
    - pandas
  # Some packages might need a `test/commands` key to check CLI.
  # List all the packages/modules that `run_test.py` imports.
  imports:
    - amici
    - amici.amici
  commands:
    - {{ PYTHON }} -m amici

about:
  home: https://github.com/amici-dev/amici
  license: BSD-3-Clause
  license_family: BSD
  #license_file: LICENSE.txt
  summary: 'Advanced Multilanguage Interface to CVODES and IDAS'

  # The remaining entries in this section are optional, but recommended.
  description: |
    AMICI provides a multi-language (Python, C++, Matlab) interface for the
    SUNDIALS solvers CVODES (for ordinary differential equations) and IDAS
    (for algebraic differential equations). AMICI allows the user to read
    differential equation models specified as SBML or PySB and automatically
    compiles such models into .mex simulation files (Matlab), C++ executables
    or Python modules.
  doc_url: https://amici.readthedocs.io/en/latest/
  dev_url: https://github.com/amici-dev/amici

extra:
  recipe-maintainers:
    - dweindl
